// SPDX-License-Identifier: GPL-3.0-or-later
//
// udl-compat - translate a Notepad++ User-Defined Language into a Scintillua lexer.
// Copyright 2026 The wxNote Authors. See LICENSE (GPL-3.0-or-later).

#include "udl_scintillua.h"

#include <sstream>

namespace udlcompat {
namespace {

// A Lua single-quoted string literal, escaping backslash and the quote. UDL
// tokens are arbitrary text (comment markers, delimiters, keywords), so this
// has to be robust rather than assume printable ASCII.
std::string luaStr(const std::string& s)
{
    std::string out = "'";
    for (char c : s) {
        if (c == '\\' || c == '\'') out += '\\';
        out += c;
    }
    out += '\'';
    return out;
}

// Scintillua's lexer name must be an identifier-ish token (it becomes a filename
// and a Lua table key). Fold anything else to '_' so an arbitrary UDL name is safe.
std::string safeName(const std::string& s)
{
    std::string out;
    for (char c : s) {
        const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                        (c >= '0' && c <= '9') || c == '_';
        out += ok ? c : '_';
    }
    if (out.empty()) out = "udl";
    return out;
}

bool anyKeywords(const UdlDef& u)
{
    for (const auto& k : u.keywords) if (!k.empty()) return true;
    return false;
}

}  // namespace

// Construct provenance (all confirmed against real Scintillua lexers / the API docs):
//   lexer.new(name)                     - every lexer's entry point
//   M:add_rule(id, patt)                - registers an ordered rule
//   M:tag(TAG, patt)                    - assigns a style tag to matched text
//   lexer.word_match('a b c', ci)       - keyword-list match (JSON/most lexers)
//   lexer.to_eol(prefix)                - line comment to end of line
//   lexer.range(open[, close])          - delimited span (strings, block comments)
//   lexer.number                        - the shared number pattern
//   lpeg.S(chars)                       - any one of a set of chars (operators); Scintillua
//                                         has no oneof(), so use LPeg's set pattern directly
//   lexer.space^1                       - whitespace run (WHITESPACE tag)
// Tags used: lexer.WHITESPACE / KEYWORD / COMMENT / STRING / NUMBER / OPERATOR,
// plus per-list KEYWORD tags "keyword2".."keyword8" so a theme can colour the
// eight UDL keyword groups distinctly (UDL's Keywords1..8 are independently styled).
std::string translateUdlToScintillua(const UdlDef& udl)
{
    const std::string name = safeName(udl.name);
    std::ostringstream o;

    o << "-- Generated by wxNote udl-compat from a Notepad++ User-Defined Language.\n";
    o << "-- Do not edit by hand; regenerate from the source userDefineLang.xml.\n";
    // `lpeg` is a global provided by Scintillua's lexer-loading environment; do NOT
    // require() it (Scintillua overrides require() in that sandbox to return the lexer).
    o << "local lexer = require('lexer')\n";
    o << "local M = lexer.new('" << name << "')\n\n";

    // Whitespace first so runs of blanks don't get retried by later rules.
    o << "M:add_rule('whitespace', M:tag(lexer.WHITESPACE, lexer.space^1))\n\n";

    // Keywords1..8, each its own rule + tag so themes can colour the groups apart.
    for (int i = 0; i < 8; ++i) {
        if (udl.keywords[i].empty()) continue;
        std::string words;
        for (size_t k = 0; k < udl.keywords[i].size(); ++k) {
            if (k) words += ' ';
            words += udl.keywords[i][k];
        }
        const std::string rule = "keyword" + std::to_string(i + 1);
        const std::string tag  = (i == 0) ? "lexer.KEYWORD" : luaStr(rule);
        o << "M:add_rule('" << rule << "', M:tag(" << tag << ", lexer.word_match("
          << luaStr(words) << (udl.keywordsCaseInsensitive ? ", true" : "") << ")))\n";
    }
    if (anyKeywords(udl)) o << '\n';

    // Comments: line (to_eol) and/or block (range), combined into one rule. Emit only when there is
    // an actual pattern: a block-comment OPEN marker with no matching CLOSE (or a close with no open)
    // is not a usable range and must not leave an empty `M:tag(lexer.COMMENT, )` argument - that is
    // invalid Lua and would make the whole generated lexer fail to load (dropping the language).
    const bool hasLineComment  = !udl.lineComment.empty();
    const bool hasBlockComment = !udl.blockCommentOpen.empty() && !udl.blockCommentClose.empty();
    if (hasLineComment || hasBlockComment) {
        o << "M:add_rule('comment', M:tag(lexer.COMMENT, ";
        if (hasLineComment)
            o << "lexer.to_eol(" << luaStr(udl.lineComment) << ")";
        if (hasBlockComment) {
            if (hasLineComment) o << " + ";
            o << "lexer.range(" << luaStr(udl.blockCommentOpen) << ", "
              << luaStr(udl.blockCommentClose) << ")";
        }
        o << "))\n";
    }

    // Delimiters -> string spans. lexer.range(open, close[, single_line? via '\n']).
    if (!udl.delimiters.empty()) {
        o << "M:add_rule('string', M:tag(lexer.STRING, ";
        for (size_t d = 0; d < udl.delimiters.size(); ++d) {
            const auto& dl = udl.delimiters[d];
            if (d) o << " + ";
            if (dl.close.empty()) {
                // single-line: range(open, '\n', true) - stop at newline, not consuming it
                o << "lexer.range(" << luaStr(dl.open) << ", '\\n', true)";
            } else if (dl.escape == "\\") {
                // Scintillua's range 'escapes' flag is specifically backslash-escaping, so enable it
                // when the UDL delimiter escapes with a backslash (the common case). Other escape
                // characters aren't representable by lexer.range and fall through to an un-escaped range.
                o << "lexer.range(" << luaStr(dl.open) << ", " << luaStr(dl.close) << ", false, true)";
            } else {
                o << "lexer.range(" << luaStr(dl.open) << ", " << luaStr(dl.close) << ")";
            }
        }
        o << "))\n";
    }

    if (udl.hasNumbers)
        o << "M:add_rule('number', M:tag(lexer.NUMBER, lexer.number))\n";

    if (!udl.operators.empty())
        o << "M:add_rule('operator', M:tag(lexer.OPERATOR, lpeg.S("
          << luaStr(udl.operators) << ")))\n";

    o << "\nreturn M\n";
    return o.str();
}

}  // namespace udlcompat
