#pragma once
// SPDX-License-Identifier: Apache-2.0
//
// keywords - the keyword lists wxNote hands its Lexilla lexers, by Language-menu language and keyword
// slot, and the words autocomplete offers from them.
//
// SciTE's, wherever SciTE has a list: keywords_scite.h, generated by tools/scite_keywords.cpp from
// SciTE's language files (plus Lexilla's own lists for Dart, Nix, TOML and Zig, from the same archive)
// and carrying their licence notice. SciTE is Lexilla's companion editor, so its lists are already
// numbered for these lexers' slots. Slots and languages it has no list for are filled below, each row
// saying where its words come from.
//
// Standalone - std only, no wx - so tests/keywords_test.cpp checks every list against the real lexers.

#include <cstddef>
#include <map>
#include <string>

struct WxnKeywordList
{
    const char* language;   // Language-menu name (menu_data_language.h), e.g. "Pascal"
    int         slot;       // the lexer's keyword set: SCI_SETKEYWORDS wParam
    const char* words;      // space-separated
};

#include "keywords_scite.h"

// Languages SciTE has no keyword lists for.
inline const WxnKeywordList* wxnExtraKeywordLists(std::size_t& n)
{
    static const WxnKeywordList t[] = {
        // wxNote's own list (Kotlin runs on the C++ lexer, so slot 0 is its keywords).
        { "Kotlin", 0,
          "abstract actual annotation as break by catch class companion const constructor continue crossinline data "
          "do dynamic else enum expect external false final finally for fun get if import in infix init inline inner "
          "interface internal is lateinit noinline null object open operator out override package private protected "
          "public reified return sealed set super suspend tailrec this throw true try typealias val var vararg when "
          "where while Int Long Float Double Boolean Char String Unit Any List Map Set" },
    };
    n = sizeof(t) / sizeof(t[0]);
    return t;
}

// Calls fn(const WxnKeywordList&) for each list `language` gets, slot by slot: SciTE's (and Lexilla's)
// wherever the generated table has that slot, the extra table's only for a slot it leaves empty.
template <class Fn>
void wxnForEachKeywordList(const std::string& language, Fn&& fn)
{
    if (language.empty()) return;
    unsigned filled = 0;   // bit per slot the generated table supplied
    std::size_t n;
    const WxnKeywordList* t = wxnSciteKeywordLists(n);
    for (std::size_t i = 0; i < n; ++i) if (language == t[i].language) { fn(t[i]); filled |= 1u << t[i].slot; }
    t = wxnExtraKeywordLists(n);
    for (std::size_t i = 0; i < n; ++i) if (language == t[i].language && !(filled & (1u << t[i].slot))) fn(t[i]);
}

// Every word `language`'s lists hold, all slots, space-separated - what autocomplete offers. Built once
// per language and kept, so the pointer stays valid for the program's life; nullptr when there are none.
inline const char* wxnKeywordWords(const std::string& language)
{
    static std::map<std::string, std::string> cache;
    auto it = cache.find(language);
    if (it == cache.end())
    {
        std::string all;
        wxnForEachKeywordList(language, [&](const WxnKeywordList& k) { if (!all.empty()) all += ' '; all += k.words; });
        it = cache.emplace(language, std::move(all)).first;
    }
    return it->second.empty() ? nullptr : it->second.c_str();
}
