#pragma once
// SPDX-License-Identifier: Apache-2.0
//
// keywords - the keyword lists wxNote hands its Lexilla lexers, by Language-menu language and keyword
// slot, and the words autocomplete offers from them.
//
// SciTE's, wherever SciTE has a list: keywords_scite.h, generated by tools/scite_keywords.cpp from
// SciTE's language files (plus Lexilla's own lists for Dart, Nix, TOML and Zig, from the same archive)
// and carrying their licence notice. SciTE is Lexilla's companion editor, so its lists are already
// numbered for these lexers' slots. Slots and languages it has no list for are filled below, each row
// saying where its words come from: wxNote's own, or other editors' lists in keywords_contrib.h, which
// carries their sources and terms.
//
// Standalone - std only, no wx - so tests/keywords_test.cpp checks every list against the real lexers.

#include <cstddef>
#include <string>

struct WxnKeywordList
{
    const char* language;   // Language-menu name (lang_table.h), e.g. "Pascal"
    int         slot;       // the lexer's keyword set: SCI_SETKEYWORDS wParam
    const char* words;      // space-separated
};

#include "keywords_scite.h"
#include "keywords_contrib.h"

// Languages SciTE has no keyword lists for.
inline const WxnKeywordList* wxnExtraKeywordLists(std::size_t& n)
{
    namespace c = wxn_contrib_keywords;
    static const WxnKeywordList t[] = {
        // Devuna's Kwik Source Search (MIT), for the case-insensitive clarionnocase lexer: keywords, compiler
        // directives, runtime expressions, built-in procedures, structures and data types, attributes,
        // standard equates, reserved labels and reserved procedure labels.
        { "Clarion", 0, c::clarion0 }, { "Clarion", 1, c::clarion1 }, { "Clarion", 2, c::clarion2 },
        { "Clarion", 3, c::clarion3 }, { "Clarion", 4, c::clarion4 }, { "Clarion", 5, c::clarion5 },
        { "Clarion", 6, c::clarion6 }, { "Clarion", 7, c::clarion7 }, { "Clarion", 8, c::clarion8 },
        // Gui4Cli's own editor, SciEd: globals, events, attributes, control statements, commands.
        { "Gui4Cli", 0, c::gui4cli0 }, { "Gui4Cli", 1, c::gui4cli1 }, { "Gui4Cli", 2, c::gui4cli2 },
        { "Gui4Cli", 3, c::gui4cli3 }, { "Gui4Cli", 4, c::gui4cli4 },
        // OpenEdge's own keyword list (abl-tmlanguage), abbreviations as "DEF(INE": keywords, the block
        // openers at a statement's start and anywhere, task markers.
        { "ABL (OpenEdge)", 0, c::abl0 }, { "ABL (OpenEdge)", 1, c::abl1 }, { "ABL (OpenEdge)", 2, c::abl2 },
        { "ABL (OpenEdge)", 3, c::abl3 },
        // BibTeX and biblatex entry types (LaTeX Workshop).
        { "BibTeX", 0, c::bibtex0 },
        // CoffeeScript's own lexer: keywords, reserved words; highlight.js: global classes.
        { "CoffeeScript", 0, c::coffeescript0 }, { "CoffeeScript", 1, c::coffeescript1 },
        { "CoffeeScript", 3, c::coffeescript3 },
        // Godot: reserved words; types and global functions.
        { "GDScript", 0, c::gdscript0 }, { "GDScript", 1, c::gdscript1 },
        // JuliaSyntax and Julia's exports: keywords, types, constants, functions.
        { "Julia", 0, c::julia0 }, { "Julia", 1, c::julia1 }, { "Julia", 2, c::julia2 }, { "Julia", 3, c::julia3 },
        // Pygments and Microsoft's documentation: statements, types, system views, @@ functions, functions,
        // system procedures, operators.
        { "MS SQL", 0, c::mssql0 }, { "MS SQL", 1, c::mssql1 }, { "MS SQL", 2, c::mssql2 }, { "MS SQL", 3, c::mssql3 },
        { "MS SQL", 4, c::mssql4 }, { "MS SQL", 5, c::mssql5 }, { "MS SQL", 6, c::mssql6 },
        // Pygments and go-mysql-server: statement verbs, keywords, objects, functions, system variables,
        // procedure keywords (the three user slots stay free).
        { "MySQL", 0, c::mysql0 }, { "MySQL", 1, c::mysql1 }, { "MySQL", 2, c::mysql2 }, { "MySQL", 3, c::mysql3 },
        { "MySQL", 4, c::mysql4 }, { "MySQL", 5, c::mysql5 },
        // Pygments and tree-sitter-stata: commands; language-stata: types.
        { "Stata", 0, c::stata0 }, { "Stata", 1, c::stata1 },
        // wxNote's own list (Kotlin runs on the C++ lexer, so slot 0 is its keywords).
        { "Kotlin", 0,
          "abstract actual annotation as break by catch class companion const constructor continue crossinline data "
          "do dynamic else enum expect external false final finally for fun get if import in infix init inline inner "
          "interface internal is lateinit noinline null object open operator out override package private protected "
          "public reified return sealed set super suspend tailrec this throw true try typealias val var vararg when "
          "where while Int Long Float Double Boolean Char String Unit Any List Map Set" },
    };
    n = sizeof(t) / sizeof(t[0]);
    return t;
}

// Calls fn(const WxnKeywordList&) for each list `language` gets, slot by slot: SciTE's (and Lexilla's)
// wherever the generated table has that slot, the extra table's only for a slot it leaves empty.
template <class Fn>
void wxnForEachKeywordList(const std::string& language, Fn&& fn)
{
    if (language.empty()) return;
    unsigned filled = 0;   // bit per slot the generated table supplied
    std::size_t n;
    const WxnKeywordList* t = wxnSciteKeywordLists(n);
    for (std::size_t i = 0; i < n; ++i) if (language == t[i].language) { fn(t[i]); filled |= 1u << t[i].slot; }
    t = wxnExtraKeywordLists(n);
    for (std::size_t i = 0; i < n; ++i) if (language == t[i].language && !(filled & (1u << t[i].slot))) fn(t[i]);
}

